// Generated from: tests\features\forget-password.feature
import { test } from "../../../fixtures/pageFixtures.ts";

test.describe('Forget Password Functionality', () => {

  test.beforeEach('Background', async ({ Given, When, Then, forgetPasswordPage, homePage, loginPage }, testInfo) => { if (testInfo.error) return;
    await Given('I navigate to the homepage', null, { homePage }); 
    await When('I click on the forget password link', null, { homePage, loginPage }); 
    await Then('I should be on the forget password page', null, { forgetPasswordPage }); 
  });
  
  test.describe('Validate successful password reset with a valid New Password', () => {

    test('Example #1', { tag: ['@smoke', '@positive'] }, async ({ Given, When, Then, And, forgetPasswordPage }) => { 
      await Given('I enter valid email "user@premiumbank.com" in forget password page', null, { forgetPasswordPage }); 
      await When('I click continue button in the forget password page', null, { forgetPasswordPage }); 
      await And('I enter valid secret code "BANK1234" in forget password page', null, { forgetPasswordPage }); 
      await When('I click verify code button in the forget password page', null, { forgetPasswordPage }); 
      await And('I enter valid current password "<currentPassword" and valid new password "Bank@456" and valid new confirm password "Bank@456"', null, { forgetPasswordPage }); 
      await When('I click reset password button in the forget password page', null, { forgetPasswordPage }); 
      await Then('I should see a successful reset password message', null, { forgetPasswordPage }); 
    });

  });

  test('Validate Error message if Email address left blank', { tag: ['@negative', '@validation'] }, async ({ Given, When, Then, forgetPasswordPage }) => { 
    await Given('I leave email input empty in forget password page', null, { forgetPasswordPage }); 
    await When('I click continue button in the forget password page', null, { forgetPasswordPage }); 
    await Then('I should see the error message of email required in the forget password page', null, { forgetPasswordPage }); 
  });

  test.describe('Validate Error message if wrong Email address entered', () => {

    test('Example #1', { tag: ['@negative', '@validation'] }, async ({ Given, When, Then, forgetPasswordPage }) => { 
      await Given('I enter invalid email "fake@mail.com" in forget password page', null, { forgetPasswordPage }); 
      await When('I click continue button in the forget password page', null, { forgetPasswordPage }); 
      await Then('I should see the error message of invalid email required in the forget password page', null, { forgetPasswordPage }); 
    });

    test('Example #2', { tag: ['@negative', '@validation'] }, async ({ Given, When, Then, forgetPasswordPage }) => { 
      await Given('I enter invalid email "notfound@xyz.io" in forget password page', null, { forgetPasswordPage }); 
      await When('I click continue button in the forget password page', null, { forgetPasswordPage }); 
      await Then('I should see the error message of invalid email required in the forget password page', null, { forgetPasswordPage }); 
    });

  });

  test.describe('Validate Error message if secret code left blank', () => {

    test('Example #1', { tag: ['@negative', '@validation'] }, async ({ Given, When, Then, And, forgetPasswordPage }) => { 
      await Given('I enter valid email "user@premiumbank.com" in forget password page', null, { forgetPasswordPage }); 
      await When('I click continue button in the forget password page', null, { forgetPasswordPage }); 
      await And('I leave secret code blank in forget password page', null, { forgetPasswordPage }); 
      await When('I click verify code button in the forget password page', null, { forgetPasswordPage }); 
      await Then('I should see the error message of secret code required in the forget password page', null, { forgetPasswordPage }); 
    });

  });

  test.describe('Validate Error message if wrong Secret Code entered', () => {

    test('Example #1', { tag: ['@negative', '@validation'] }, async ({ Given, When, Then, And, forgetPasswordPage }) => { 
      await Given('I enter valid email "user@premiumbank.com" in forget password page', null, { forgetPasswordPage }); 
      await When('I click continue button in the forget password page', null, { forgetPasswordPage }); 
      await And('I enter invalid secret code "000000" in forget password page', null, { forgetPasswordPage }); 
      await When('I click verify code button in the forget password page', null, { forgetPasswordPage }); 
      await Then('I should see the error message of invalid secret code in the forget password page', null, { forgetPasswordPage }); 
    });

  });

  test.describe('Validate Error message if Current Password left blank', () => {

    test('Example #1', { tag: ['@negative', '@validation'] }, async ({ Given, When, Then, And, forgetPasswordPage }) => { 
      await Given('I enter valid email "user@premiumbank.com" in forget password page', null, { forgetPasswordPage }); 
      await When('I click continue button in the forget password page', null, { forgetPasswordPage }); 
      await And('I enter valid secret code "BANK1234" in forget password page', null, { forgetPasswordPage }); 
      await When('I click verify code button in the forget password page', null, { forgetPasswordPage }); 
      await And('I leave current password blank and valid new password "Bank@456" and valid new confirm password "Bank@456"', null, { forgetPasswordPage }); 
      await When('I click reset password button in the forget password page', null, { forgetPasswordPage }); 
      await Then('I should see the error message of current password required in the forget password page', null, { forgetPasswordPage }); 
    });

  });

  test.describe('Validate Error message if New Password left blank', () => {

    test('Example #1', { tag: ['@negative', '@validation'] }, async ({ Given, When, Then, And, forgetPasswordPage }) => { 
      await Given('I enter valid email "user@premiumbank.com" in forget password page', null, { forgetPasswordPage }); 
      await When('I click continue button in the forget password page', null, { forgetPasswordPage }); 
      await And('I enter valid secret code "BANK1234" in forget password page', null, { forgetPasswordPage }); 
      await When('I click verify code button in the forget password page', null, { forgetPasswordPage }); 
      await And('I enter valid current password "<currentPassword" and leave new password blank and enter valid new confirm password "Bank@456"', null, { forgetPasswordPage }); 
      await When('I click reset password button in the forget password page', null, { forgetPasswordPage }); 
      await Then('I should see the error message of new password required in the forget password page', null, { forgetPasswordPage }); 
    });

  });

  test.describe('Validate Error message if Confirm New Password left blank', () => {

    test('Example #1', { tag: ['@negative', '@validation'] }, async ({ Given, When, Then, And, forgetPasswordPage }) => { 
      await Given('I enter valid email "user@premiumbank.com" in forget password page', null, { forgetPasswordPage }); 
      await When('I click continue button in the forget password page', null, { forgetPasswordPage }); 
      await And('I enter valid secret code "BANK1234" in forget password page', null, { forgetPasswordPage }); 
      await When('I click verify code button in the forget password page', null, { forgetPasswordPage }); 
      await And('I enter valid current password "<currentPassword" and valid new password "Bank@456" and leave new confirm password blank', null, { forgetPasswordPage }); 
      await When('I click reset password button in the forget password page', null, { forgetPasswordPage }); 
      await Then('I should see the error message of new confirm password required in the forget password page', null, { forgetPasswordPage }); 
    });

  });

  test.describe('Validate error message if New and Confirm Password do not match', () => {

    test('Example #1', { tag: ['@negative', '@validation'] }, async ({ Given, When, Then, And, forgetPasswordPage }) => { 
      await Given('I enter valid email "user@premiumbank.com" in forget password page', null, { forgetPasswordPage }); 
      await When('I click continue button in the forget password page', null, { forgetPasswordPage }); 
      await And('I enter valid secret code "BANK1234" in forget password page', null, { forgetPasswordPage }); 
      await When('I click verify code button in the forget password page', null, { forgetPasswordPage }); 
      await And('I enter valid current password "<currentPassword" and valid new password "Bank@456" and invalid new confirm password "Bank@789"', null, { forgetPasswordPage }); 
      await When('I click reset password button in the forget password page', null, { forgetPasswordPage }); 
      await Then('I should see the error message of mismatched password in the forget password page', null, { forgetPasswordPage }); 
    });

  });

  test.describe('Validate error message if New and Confirm Password do not meet password criteria', () => {

    test('Example #1', { tag: ['@validation', '@security', '@ui'] }, async ({ Given, When, Then, And, forgetPasswordPage }) => { 
      await Given('I enter valid email "user@premiumbank.com" in forget password page', null, { forgetPasswordPage }); 
      await When('I click continue button in the forget password page', null, { forgetPasswordPage }); 
      await And('I enter valid secret code "BANK1234" in forget password page', null, { forgetPasswordPage }); 
      await When('I click verify code button in the forget password page', null, { forgetPasswordPage }); 
      await And('I enter valid current password "Bank@123" and invalid new password "weakpass" and invalid new confirm password "weakpass"', null, { forgetPasswordPage }); 
      await Then('I should see the color change of password criteria in the forget password page', null, { forgetPasswordPage }); 
    });

  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('tests\\features\\forget-password.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":14,"pickleLine":22,"tags":["@smoke","@positive"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given I navigate to the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When I click on the forget password link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then I should be on the forget password page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":15,"gherkinStepLine":12,"keywordType":"Context","textWithKeyword":"Given I enter valid email \"user@premiumbank.com\" in forget password page","stepMatchArguments":[{"group":{"start":20,"value":"\"user@premiumbank.com\"","children":[{"start":21,"value":"user@premiumbank.com","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":16,"gherkinStepLine":13,"keywordType":"Action","textWithKeyword":"When I click continue button in the forget password page","stepMatchArguments":[]},{"pwStepLine":17,"gherkinStepLine":14,"keywordType":"Action","textWithKeyword":"And I enter valid secret code \"BANK1234\" in forget password page","stepMatchArguments":[{"group":{"start":26,"value":"\"BANK1234\"","children":[{"start":27,"value":"BANK1234","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":18,"gherkinStepLine":15,"keywordType":"Action","textWithKeyword":"When I click verify code button in the forget password page","stepMatchArguments":[]},{"pwStepLine":19,"gherkinStepLine":16,"keywordType":"Action","textWithKeyword":"And I enter valid current password \"<currentPassword\" and valid new password \"Bank@456\" and valid new confirm password \"Bank@456\"","stepMatchArguments":[{"group":{"start":31,"value":"\"<currentPassword\"","children":[{"start":32,"value":"<currentPassword","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":73,"value":"\"Bank@456\"","children":[{"start":74,"value":"Bank@456","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":115,"value":"\"Bank@456\"","children":[{"start":116,"value":"Bank@456","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":20,"gherkinStepLine":17,"keywordType":"Action","textWithKeyword":"When I click reset password button in the forget password page","stepMatchArguments":[]},{"pwStepLine":21,"gherkinStepLine":18,"keywordType":"Outcome","textWithKeyword":"Then I should see a successful reset password message","stepMatchArguments":[]}]},
  {"pwTestLine":26,"pickleLine":25,"tags":["@negative","@validation"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given I navigate to the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When I click on the forget password link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then I should be on the forget password page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":27,"gherkinStepLine":26,"keywordType":"Context","textWithKeyword":"Given I leave email input empty in forget password page","stepMatchArguments":[]},{"pwStepLine":28,"gherkinStepLine":27,"keywordType":"Action","textWithKeyword":"When I click continue button in the forget password page","stepMatchArguments":[]},{"pwStepLine":29,"gherkinStepLine":28,"keywordType":"Outcome","textWithKeyword":"Then I should see the error message of email required in the forget password page","stepMatchArguments":[]}]},
  {"pwTestLine":34,"pickleLine":38,"tags":["@negative","@validation"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given I navigate to the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When I click on the forget password link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then I should be on the forget password page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":35,"gherkinStepLine":32,"keywordType":"Context","textWithKeyword":"Given I enter invalid email \"fake@mail.com\" in forget password page","stepMatchArguments":[{"group":{"start":22,"value":"\"fake@mail.com\"","children":[{"start":23,"value":"fake@mail.com","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":36,"gherkinStepLine":33,"keywordType":"Action","textWithKeyword":"When I click continue button in the forget password page","stepMatchArguments":[]},{"pwStepLine":37,"gherkinStepLine":34,"keywordType":"Outcome","textWithKeyword":"Then I should see the error message of invalid email required in the forget password page","stepMatchArguments":[]}]},
  {"pwTestLine":40,"pickleLine":39,"tags":["@negative","@validation"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given I navigate to the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When I click on the forget password link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then I should be on the forget password page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":41,"gherkinStepLine":32,"keywordType":"Context","textWithKeyword":"Given I enter invalid email \"notfound@xyz.io\" in forget password page","stepMatchArguments":[{"group":{"start":22,"value":"\"notfound@xyz.io\"","children":[{"start":23,"value":"notfound@xyz.io","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":42,"gherkinStepLine":33,"keywordType":"Action","textWithKeyword":"When I click continue button in the forget password page","stepMatchArguments":[]},{"pwStepLine":43,"gherkinStepLine":34,"keywordType":"Outcome","textWithKeyword":"Then I should see the error message of invalid email required in the forget password page","stepMatchArguments":[]}]},
  {"pwTestLine":50,"pickleLine":50,"tags":["@negative","@validation"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given I navigate to the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When I click on the forget password link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then I should be on the forget password page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":51,"gherkinStepLine":42,"keywordType":"Context","textWithKeyword":"Given I enter valid email \"user@premiumbank.com\" in forget password page","stepMatchArguments":[{"group":{"start":20,"value":"\"user@premiumbank.com\"","children":[{"start":21,"value":"user@premiumbank.com","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":52,"gherkinStepLine":43,"keywordType":"Action","textWithKeyword":"When I click continue button in the forget password page","stepMatchArguments":[]},{"pwStepLine":53,"gherkinStepLine":44,"keywordType":"Action","textWithKeyword":"And I leave secret code blank in forget password page","stepMatchArguments":[]},{"pwStepLine":54,"gherkinStepLine":45,"keywordType":"Action","textWithKeyword":"When I click verify code button in the forget password page","stepMatchArguments":[]},{"pwStepLine":55,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"Then I should see the error message of secret code required in the forget password page","stepMatchArguments":[]}]},
  {"pwTestLine":62,"pickleLine":63,"tags":["@negative","@validation"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given I navigate to the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When I click on the forget password link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then I should be on the forget password page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":63,"gherkinStepLine":55,"keywordType":"Context","textWithKeyword":"Given I enter valid email \"user@premiumbank.com\" in forget password page","stepMatchArguments":[{"group":{"start":20,"value":"\"user@premiumbank.com\"","children":[{"start":21,"value":"user@premiumbank.com","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":64,"gherkinStepLine":56,"keywordType":"Action","textWithKeyword":"When I click continue button in the forget password page","stepMatchArguments":[]},{"pwStepLine":65,"gherkinStepLine":57,"keywordType":"Action","textWithKeyword":"And I enter invalid secret code \"000000\" in forget password page","stepMatchArguments":[{"group":{"start":28,"value":"\"000000\"","children":[{"start":29,"value":"000000","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":66,"gherkinStepLine":58,"keywordType":"Action","textWithKeyword":"When I click verify code button in the forget password page","stepMatchArguments":[]},{"pwStepLine":67,"gherkinStepLine":59,"keywordType":"Outcome","textWithKeyword":"Then I should see the error message of invalid secret code in the forget password page","stepMatchArguments":[]}]},
  {"pwTestLine":74,"pickleLine":78,"tags":["@negative","@validation"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given I navigate to the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When I click on the forget password link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then I should be on the forget password page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":75,"gherkinStepLine":68,"keywordType":"Context","textWithKeyword":"Given I enter valid email \"user@premiumbank.com\" in forget password page","stepMatchArguments":[{"group":{"start":20,"value":"\"user@premiumbank.com\"","children":[{"start":21,"value":"user@premiumbank.com","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":76,"gherkinStepLine":69,"keywordType":"Action","textWithKeyword":"When I click continue button in the forget password page","stepMatchArguments":[]},{"pwStepLine":77,"gherkinStepLine":70,"keywordType":"Action","textWithKeyword":"And I enter valid secret code \"BANK1234\" in forget password page","stepMatchArguments":[{"group":{"start":26,"value":"\"BANK1234\"","children":[{"start":27,"value":"BANK1234","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":78,"gherkinStepLine":71,"keywordType":"Action","textWithKeyword":"When I click verify code button in the forget password page","stepMatchArguments":[]},{"pwStepLine":79,"gherkinStepLine":72,"keywordType":"Action","textWithKeyword":"And I leave current password blank and valid new password \"Bank@456\" and valid new confirm password \"Bank@456\"","stepMatchArguments":[{"group":{"start":54,"value":"\"Bank@456\"","children":[{"start":55,"value":"Bank@456","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":96,"value":"\"Bank@456\"","children":[{"start":97,"value":"Bank@456","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":80,"gherkinStepLine":73,"keywordType":"Action","textWithKeyword":"When I click reset password button in the forget password page","stepMatchArguments":[]},{"pwStepLine":81,"gherkinStepLine":74,"keywordType":"Outcome","textWithKeyword":"Then I should see the error message of current password required in the forget password page","stepMatchArguments":[]}]},
  {"pwTestLine":88,"pickleLine":92,"tags":["@negative","@validation"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given I navigate to the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When I click on the forget password link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then I should be on the forget password page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":89,"gherkinStepLine":82,"keywordType":"Context","textWithKeyword":"Given I enter valid email \"user@premiumbank.com\" in forget password page","stepMatchArguments":[{"group":{"start":20,"value":"\"user@premiumbank.com\"","children":[{"start":21,"value":"user@premiumbank.com","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":90,"gherkinStepLine":83,"keywordType":"Action","textWithKeyword":"When I click continue button in the forget password page","stepMatchArguments":[]},{"pwStepLine":91,"gherkinStepLine":84,"keywordType":"Action","textWithKeyword":"And I enter valid secret code \"BANK1234\" in forget password page","stepMatchArguments":[{"group":{"start":26,"value":"\"BANK1234\"","children":[{"start":27,"value":"BANK1234","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":92,"gherkinStepLine":85,"keywordType":"Action","textWithKeyword":"When I click verify code button in the forget password page","stepMatchArguments":[]},{"pwStepLine":93,"gherkinStepLine":86,"keywordType":"Action","textWithKeyword":"And I enter valid current password \"<currentPassword\" and leave new password blank and enter valid new confirm password \"Bank@456\"","stepMatchArguments":[{"group":{"start":31,"value":"\"<currentPassword\"","children":[{"start":32,"value":"<currentPassword","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":116,"value":"\"Bank@456\"","children":[{"start":117,"value":"Bank@456","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":94,"gherkinStepLine":87,"keywordType":"Action","textWithKeyword":"When I click reset password button in the forget password page","stepMatchArguments":[]},{"pwStepLine":95,"gherkinStepLine":88,"keywordType":"Outcome","textWithKeyword":"Then I should see the error message of new password required in the forget password page","stepMatchArguments":[]}]},
  {"pwTestLine":102,"pickleLine":106,"tags":["@negative","@validation"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given I navigate to the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When I click on the forget password link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then I should be on the forget password page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":103,"gherkinStepLine":96,"keywordType":"Context","textWithKeyword":"Given I enter valid email \"user@premiumbank.com\" in forget password page","stepMatchArguments":[{"group":{"start":20,"value":"\"user@premiumbank.com\"","children":[{"start":21,"value":"user@premiumbank.com","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":104,"gherkinStepLine":97,"keywordType":"Action","textWithKeyword":"When I click continue button in the forget password page","stepMatchArguments":[]},{"pwStepLine":105,"gherkinStepLine":98,"keywordType":"Action","textWithKeyword":"And I enter valid secret code \"BANK1234\" in forget password page","stepMatchArguments":[{"group":{"start":26,"value":"\"BANK1234\"","children":[{"start":27,"value":"BANK1234","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":106,"gherkinStepLine":99,"keywordType":"Action","textWithKeyword":"When I click verify code button in the forget password page","stepMatchArguments":[]},{"pwStepLine":107,"gherkinStepLine":100,"keywordType":"Action","textWithKeyword":"And I enter valid current password \"<currentPassword\" and valid new password \"Bank@456\" and leave new confirm password blank","stepMatchArguments":[{"group":{"start":31,"value":"\"<currentPassword\"","children":[{"start":32,"value":"<currentPassword","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":73,"value":"\"Bank@456\"","children":[{"start":74,"value":"Bank@456","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":108,"gherkinStepLine":101,"keywordType":"Action","textWithKeyword":"When I click reset password button in the forget password page","stepMatchArguments":[]},{"pwStepLine":109,"gherkinStepLine":102,"keywordType":"Outcome","textWithKeyword":"Then I should see the error message of new confirm password required in the forget password page","stepMatchArguments":[]}]},
  {"pwTestLine":116,"pickleLine":120,"tags":["@negative","@validation"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given I navigate to the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When I click on the forget password link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then I should be on the forget password page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":117,"gherkinStepLine":110,"keywordType":"Context","textWithKeyword":"Given I enter valid email \"user@premiumbank.com\" in forget password page","stepMatchArguments":[{"group":{"start":20,"value":"\"user@premiumbank.com\"","children":[{"start":21,"value":"user@premiumbank.com","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":118,"gherkinStepLine":111,"keywordType":"Action","textWithKeyword":"When I click continue button in the forget password page","stepMatchArguments":[]},{"pwStepLine":119,"gherkinStepLine":112,"keywordType":"Action","textWithKeyword":"And I enter valid secret code \"BANK1234\" in forget password page","stepMatchArguments":[{"group":{"start":26,"value":"\"BANK1234\"","children":[{"start":27,"value":"BANK1234","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":120,"gherkinStepLine":113,"keywordType":"Action","textWithKeyword":"When I click verify code button in the forget password page","stepMatchArguments":[]},{"pwStepLine":121,"gherkinStepLine":114,"keywordType":"Action","textWithKeyword":"And I enter valid current password \"<currentPassword\" and valid new password \"Bank@456\" and invalid new confirm password \"Bank@789\"","stepMatchArguments":[{"group":{"start":31,"value":"\"<currentPassword\"","children":[{"start":32,"value":"<currentPassword","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":73,"value":"\"Bank@456\"","children":[{"start":74,"value":"Bank@456","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":117,"value":"\"Bank@789\"","children":[{"start":118,"value":"Bank@789","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":122,"gherkinStepLine":115,"keywordType":"Action","textWithKeyword":"When I click reset password button in the forget password page","stepMatchArguments":[]},{"pwStepLine":123,"gherkinStepLine":116,"keywordType":"Outcome","textWithKeyword":"Then I should see the error message of mismatched password in the forget password page","stepMatchArguments":[]}]},
  {"pwTestLine":130,"pickleLine":133,"tags":["@validation","@security","@ui"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given I navigate to the homepage","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When I click on the forget password link","isBg":true,"stepMatchArguments":[]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then I should be on the forget password page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":131,"gherkinStepLine":124,"keywordType":"Context","textWithKeyword":"Given I enter valid email \"user@premiumbank.com\" in forget password page","stepMatchArguments":[{"group":{"start":20,"value":"\"user@premiumbank.com\"","children":[{"start":21,"value":"user@premiumbank.com","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":132,"gherkinStepLine":125,"keywordType":"Action","textWithKeyword":"When I click continue button in the forget password page","stepMatchArguments":[]},{"pwStepLine":133,"gherkinStepLine":126,"keywordType":"Action","textWithKeyword":"And I enter valid secret code \"BANK1234\" in forget password page","stepMatchArguments":[{"group":{"start":26,"value":"\"BANK1234\"","children":[{"start":27,"value":"BANK1234","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":134,"gherkinStepLine":127,"keywordType":"Action","textWithKeyword":"When I click verify code button in the forget password page","stepMatchArguments":[]},{"pwStepLine":135,"gherkinStepLine":128,"keywordType":"Action","textWithKeyword":"And I enter valid current password \"Bank@123\" and invalid new password \"weakpass\" and invalid new confirm password \"weakpass\"","stepMatchArguments":[{"group":{"start":31,"value":"\"Bank@123\"","children":[{"start":32,"value":"Bank@123","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":67,"value":"\"weakpass\"","children":[{"start":68,"value":"weakpass","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":111,"value":"\"weakpass\"","children":[{"start":112,"value":"weakpass","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":136,"gherkinStepLine":129,"keywordType":"Outcome","textWithKeyword":"Then I should see the color change of password criteria in the forget password page","stepMatchArguments":[]}]},
]; // bdd-data-end