name: Playwright tests (CI)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: "npm" # optional built-in cache from setup-node

      - name: Cache Playwright browsers
        id: cache-browsers
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers (only what we need)
        run: npx playwright install --with-deps

      - name: Load .env.example into environment
        run: |
          if [ -f .env.example ]; then
            echo "Loading from .env.example"
            # Remove CR characters, filter comments, then output each key=value to $GITHUB_ENV
            sed 's/\r$//' .env.example | grep -v '^#' | while IFS='=' read -r key value; do
              # optionally trim quotes/spaces
              echo "${key}=${value}" >> $GITHUB_ENV
            done
          else
            echo "No .env.example file found"
          fi

      - name: Debug environment
        run: |
          echo "BASE_URL is: $BASE_URL"

      # - name: Run Playwright BDD tests
      #   env:
      #     CI: "true"
      #     HEADLESS: "true"
          # BASE_URL: ${{ secrets.BASE_URL }}
        # run: |
        #   # optionally limit workers or run a shard
        #   # npx playwright test --reporter=list
        #   npx bddgen && npx playwright test --reporter=list,allure-playwright

        # 🚀 Step 7: Run *important* tests first (e.g. smoke, positive)
      - name: Run Priority Playwright BDD tests (@smoke, @positive)
        env:
          CI: "true"
          HEADLESS: "true"
        run: |
          npx bddgen
          npx playwright test --grep "@smoke|@positive" --reporter=list,allure-playwright

      # ⚙️ Step 8: Run remaining tests (everything else)
      - name: Run Remaining Playwright BDD tests
        if: always() # run even if smoke tests failed
        env:
          CI: "true"
          HEADLESS: "true"
        run: |
          npx bddgen
          npx playwright test --grep-invert "@smoke|@positive" --reporter=list,allure-playwright

      - name: Generate Allure HTML report
              # Run this even if tests fail so you can inspect results
        if: always()
        run: |
          npx allure generate ./allure-results --clean -o allure-report

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30

      - name: Upload Playwright report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload traces/videos/screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            test-results/
            traces/
            videos/
          retention-days: 30
