name: Playwright tests (CI)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: "npm" # optional built-in cache from setup-node

      - name: Cache Playwright browsers
        id: cache-browsers
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers (only what we need)
        run: npx playwright install --with-deps

      - name: Load .env.example
        run: |
          if [ -f .env.example ]; then
            echo "Loading environment variables from .env.example"
            set -a
            # Remove carriage returns and comments
            sed 's/\r$//' .env.example | grep -v '^#' > .env.tmp
            source .env.tmp
            set +a
            rm .env.tmp
          else
            echo "No .env.example file found"
          fi

      - name: Debug environment
        run: printenv | grep BASE_URL || echo "BASE_URL not found"

      - name: Run Playwright tests
        env:
          CI: "true"
          HEADLESS: "true"
          # BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          # optionally limit workers or run a shard
          # npx playwright test --reporter=list
          npx bddgen && npx playwright test --reporter=list

      - name: Upload Playwright report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload traces/videos/screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            test-results/
            traces/
            videos/
          retention-days: 30
